### ISSUE TITLE
Separate Summary and TOC

### ISSUE THREAD

**Issue by SteveALee** [w3c/wai-coga-design-guide#18]
The attempt at combining The Coga Summary and TOC was deemed too complex.

- [x] Use a 3 level TOC like [All Understanding Pages](https://draft-wcag-redesign.netlify.app/understanding/)
- [x] create a new WAI page "Coga Patterns at  a Glance" based on Coga Summary and located under https://www.w3.org/WAI/cognitive/

**Comment by SteveALee** [comment]
@nitedog @hidde @shawna-slh 

As well as reworking the [ToC page](https://deploy-preview-10--wai-coga-design-guide.netlify.app/supplemental-guidance/) I also mocked up how the ["At a Glance"](https://deploy-preview-10--wai-coga-design-guide.netlify.app/coga-patterns-glance/) page might look like based on the [WCAG one](https://www.w3.org/WAI/standards-guidelines/wcag/glance/).

The thing is they are pretty much the same thing. At least while the ToC is coga only. Or rather the "Coga At A Glace" would have been almost the same as a differently styled "ToC". This is as the WCAG AaG has the related links below it. For coga I replaced this with the Content Usable summary section content to be found as this is what COga TF want. If we add the links back it looks like the old coga ToC which we felt was too busy.

What do you think?

Note, that now if someone follows the AaG "Read More" link to an objective then there is no quick way to navigate to the list of patterns for that objective (they will be soon removed from the sidebar). So should we add all the pattern links below the objective summary text.

It might be better to have a meeting to discuss this.

**Comment by nitedog** [comment]
Happy to discuss!

Have you considered listing the patterns at the bottom of the objectives (in the main body, after the paragraphs describing the objective)? Here is an [example Understanding document on a Guideline level](https://draft-wcag-redesign.netlify.app/understanding/time-based-media) that lists the Understanding documents on the Success Criteria below this Guideline - maybe we can use the same approach here?

**Comment by SteveALee** [comment]
> I wonder if the the "COGA At a Glance" should be stand-alone on 

That is the intention - there's a note at the top of the page to state that. Should find how to make a coloured note so it stands out as an editorial comment. We will then lose the ability generate the content from code but that's not a problem at all.

>  I think the primary audience for both resources may be fairly distinct

Agree. Plus the ToC will probably expand to cover low vision etc.

> Have you considered listing the patterns at the bottom of the objectives

Yes and that is my favourite option - I meant to mention that.
