### ISSUE TITLE
Improve “About this page” content

### ISSUE THREAD

**Issue by hidde** [w3c/wai-coga-design-guide#5]
Currently we have a box with a heading “About this page”  and this content: 

> COGA Design Patterns are supplemental guidance beyond the requirements of WCAG. 

@SteveALee @nitedog What would be a better 1-2 sentence description of these docs?

**Comment by SteveALee** [comment]
Options seem to be:
a) Scavenge the content from the [design guide introduction](https://w3c.github.io/coga/content-usable/#design_for_everyone) after getting TF to accept suggested improvements
b) provide something specific for this 'version' - but with TF approval

**Comment by hidde** [comment]
I have copied the design guide introduction to the [About](https://wai-coga-design-guide.netlify.app/about/) page.

For the “About this page“ box, I think we need more of an ‘elevator’ pitch, ideally one that works in a building with very few floors. It's meant to be a very short answer to “What am I looking at? How does it fit in with WCAG?“. For instance, for Techniques the current draft is “Techniques are examples of ways to meet a WCAG success criterion.”

**Comment by SteveALee** [comment]
Probably use summary section form content usable - with icons

**Comment by SteveALee** [comment]
See #13

**Comment by SteveALee** [comment]
Info common to all patterns can go here rather than the pattern side bars - see #7
